### ISSUE TITLE
Any problems?

### ISSUE THREAD

**Issue by mengkunsoft** [mengkunsoft/MKOnlineMusicPlayer#1]
Please use 'Issues'!

**Comment by imxintian** [comment]
你好，fork之后，用gitpage打开，里面的搜索功能不能正常使用，显示“搜索结果获取失败-405”，请问怎么解决？

**Comment by mengkunsoft** [comment]
@imxintian 本程序依赖 PHP 环境，需要上传至支持 PHP 的空间使用

**Comment by imxintian** [comment]
谢谢，请问你是买的服务器吗？如果以GitHub作为服务器该如何操作？

**Comment by mengkunsoft** [comment]
@imxintian 我是放在腾讯云服务器上运行的。GitHub Page 好像只能运行静态页面吧？没研究过

**Comment by mengkunsoft** [comment]
![播放列表界面(电脑端)](https://ws3.sinaimg.cn/large/a15b4afegy1fjkige7cf3j211y0hqh0p.jpg)

**Comment by mashirozx** [comment]
你好，前几天似乎一直正常的，今天忽然遇到这样的问题：有的歌曲加载失败（其他则仍能成功），报错如下：

![image](https://user-images.githubusercontent.com/16148054/30870059-647e1a0c-a315-11e7-9b6d-01a5d44e4a4d.png)

这个报错链接实从console打开却能播放，怀疑是否是因为我用的是国外服务器？

出错歌曲是这首：http://music.163.com/m/song?id=29392565&userid=2655217

非常感谢！

**Comment by mashirozx** [comment]
抱歉打扰，我用你服务器上的播放器试了这首歌能播放，那么基本可以确定是我的问题了吗？

我记得上一版的播放器有一个代理功能，但是这次更新后似乎取消了？

**Comment by mashirozx** [comment]
发现另一个以Meeting为基础的WordPress插件（Hermit-X）也出现了类似的问题，这说明是Meeting的问题？

**Comment by mengkunsoft** [comment]
@mashirozx 非常感谢这么详细的反馈。这种情况应该是 网易云 对 歌曲外链做出了限制引起的。正在研究解决办法中。

**Comment by markruan** [comment]
获取音乐地址的办法

当获取到音乐的 id 后，将 http://music.163.com/song/media/outer/url?id={id}.mp3 以src 赋予 Audio即可播放

**Comment by mengkunsoft** [comment]
@markruan 这个接口非常不错！感谢分享！

**Comment by DanielZhang17** [comment]
网易的又挂了，目测歌单也无法正常读取了，腾讯的播放正常，估计接口又改了？

**Comment by wangsaizzy** [comment]
您好，网站：http://1942ys.com/  各种报405错误，对PHP方面不太熟，不知道什么原因，还望指教

**Comment by mengkunsoft** [comment]
@wangsaizzy 你的服务器没有安装 PHP 运行环境引起的

**Comment by 657228932** [comment]
php是 5.4  在mac os上面的safari打开就-404，我在Google就可以打开，请问正确的打开姿势是什么？

**Comment by Honjeans** [comment]
坤大哥你好，我的放上了服务器发现，谷歌浏览器和微软edge浏览器正常使用，但是火狐和360浏览器无法打开，显示域名解析错误，域名是music.djunonline.com.另外苹果手机的safari有点不兼容，有点难点击。主要是想解决浏览器打开的问题，刚刚学前端，望指点下，非常感谢
