### ISSUE TITLE
建议移动端增加左右滑动切换

### ISSUE THREAD

**Issue by markruan** [mengkunsoft/MKOnlineMusicPlayer#11]
首先非常感谢你的分享，我已经用在可我的网站，建议增加移动端左右滑动切换列表，那就更好了，谢谢

**Comment by mengkunsoft** [comment]
要做成左右滑动的效果，需要页面上缓存左右两边的列表（界面）。迫于移动端浏览器内存的限制，这样做的话会导致非常卡，反而没有现在的切换方式这么流畅。所以没有加入。
