### ISSUE TITLE
导入网易云个人喜欢音乐歌单只能显示1k首

### ISSUE THREAD

**Issue by CHN-STUDENT** [mengkunsoft/MKOnlineMusicPlayer#12]
我网易云个人音乐歌单收藏了大约1.7k首，但是导入成功之后只有1k首在列表上？

**Comment by mengkunsoft** [comment]
因为网页版的限制，如果列表中的项目过多，可能会导致播放器**非常卡顿**。因此程序中默认限制了用户歌单数以及歌单中的音乐上限为 1000

如果想要提高歌单中的**音乐**上限，可以手动将 `/plugns/Meting.php` [第 479 行](https://github.com/mengkunsoft/MKOnlineMusicPlayer/blob/master/plugns/Meting.php#L479)的 `"n"  => 1000,` 改成你想要的数值。

如果想要提高**歌单**上限，可以手动将 `api.php` [第 72 行](https://github.com/mengkunsoft/MKOnlineMusicPlayer/blob/master/api.php#L72)  的 `limit=1001` 修改成你想要的数值
