### ISSUE TITLE
为什么打开页面后只有一首歌曲

### ISSUE THREAD

**Issue by eastspectral** [mengkunsoft/MKOnlineMusicPlayer#24]
除了搜索除网易之外，其它方式获取的歌曲都只有一首，比如获取用户歌单，歌单获取了，点击里面却只有一首歌曲，而且所有列表里面都只有一首

**Comment by mengkunsoft** [comment]
参阅 [https://github.com/mengkunsoft/MKOnlineMusicPlayer/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E9%97%AE%E9%A2%98](https://github.com/mengkunsoft/MKOnlineMusicPlayer/wiki/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E9%97%AE%E9%A2%98)
