### ISSUE TITLE
播放网易云歌单会导致陷入无法播放的死循环

### ISSUE THREAD

**Issue by zyh001** [mengkunsoft/MKOnlineMusicPlayer#26]
此前我已经导入了自己的cookie信息，但有相当大的几率会陷入循环，只有极少数情况可以播放成功

**Comment by shoucanjun** [comment]
我也是

**Comment by zyh001** [comment]
@shoucanjun 对于网易云，解决方案可以是，先生成外链，然后在服务器上保存下来，再从服务器上进行播放和下载，这样是没有问题的，只不过会耗费服务器流量

**Comment by hucstar** [comment]
心疼老哥，找了好多不能用，盗版都盗不好，原来真尊在这里！

**Comment by mengkunsoft** [comment]
新版已解决
