### ISSUE TITLE
播放列表(歌单)读取

### ISSUE THREAD

**Issue by AlliotTech** [mengkunsoft/MKOnlineMusicPlayer#29]
播放列表(歌单)读取失败

**Comment by q1374147274** [comment]
https://github.com/mengkunsoft/MKOnlineMusicPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

里面第一个是解决播放列表只有一条的问题

**Comment by AlliotTech** [comment]
嗯嗯  这个我看了。。。

**Comment by mengkunsoft** [comment]
新版已解决此问题
