### ISSUE TITLE
demo网址下载音乐名称是一串无意义字母

### ISSUE THREAD

**Issue by cjd6568358** [mengkunsoft/MKOnlineMusicPlayer#32]
浏览器版本：chrome 64

![image](https://user-images.githubusercontent.com/3970494/37635700-407699e8-2c38-11e8-8dea-090c0379b7e1.png)

**Comment by mengkunsoft** [comment]
https://github.com/mengkunsoft/MKOnlineMusicPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%8B%E8%BD%BD%E6%AD%8C%E6%9B%B2%E7%9A%84%E6%96%87%E4%BB%B6%E5%90%8D%E4%B8%BA%E4%B9%B1%E7%A0%81
