### ISSUE TITLE
请问歌单的登陆信息是如何保存的？

### ISSUE THREAD

**Issue by mashirozx** [mengkunsoft/MKOnlineMusicPlayer#33]
是这样的，把播放器设置成了桌面（某个可以把HTML设为壁纸的软件），然而桌面上无法输入账号，想直接导入ｃｏｏｋｉｅ实现登陆，结果发现浏览器上似乎没有cookie 😓

求解QAQ

![image](https://user-images.githubusercontent.com/16148054/38508165-fcdb75cc-3c50-11e8-838f-993160684653.png)

**Comment by mengkunsoft** [comment]
播放器所有的本地信息都存储在 localstorage 中

**Comment by mashirozx** [comment]
@mengkunsoft  谢谢~
