### ISSUE TITLE
歌单读取200错误，php版本7.2.5

### ISSUE THREAD

**Issue by mojingsiyun** [mengkunsoft/MKOnlineMusicPlayer#44]
目前只有播放列表-自定义列表-特别的爱给特别的你.mp3 可以正常播放，其他都是200错误。求解，调试模式已开启。
补充：网易接口全部报错200，QQ搜索播放正常，虾米   酷狗   百度 网易全部200
http://modian.eicp.net:81/music

**Comment by mengkunsoft** [comment]
开启服务器对 `openssl_encrypt` 或 `mcrypt_encrypt` 函数的支持即可。
（操作方法自行百度）
