### ISSUE TITLE
部分歌曲背景过浅

### ISSUE THREAD

**Issue by xiaomage2000** [mengkunsoft/MKOnlineMusicPlayer#45]
部分歌曲专辑封面颜色过浅，导致播放器背景过浅，很多字看不清楚，请问这个背景可以关掉吗？或者有什么好的改善方法吗？

**Comment by xiaomage2000** [comment]
![screenshot_20180720-222802__01](https://user-images.githubusercontent.com/13915895/43008488-d1356e24-8c6d-11e8-8397-2272484b6110.jpg)
具体症状如图

**Comment by mengkunsoft** [comment]
https://github.com/mengkunsoft/MKOnlineMusicPlayer/blob/master/js/player.js#L15
