### ISSUE TITLE
MKOnlineMusicPlayer develop like aplayer HTML5 LRC

### ISSUE THREAD

**Issue by tuannvbg** [mengkunsoft/MKOnlineMusicPlayer#5]
Thanks for created play very like. I Think you develop name "MKMusicPlayer" like aplayer html5 (https://github.com/MoePlayer/APlayer) I will add my website for music website. Thanks you!

**Comment by mengkunsoft** [comment]
APlayer 也是我一直在关注的一个项目。相比之下，它的代码要优美得多 :smile:
