### ISSUE TITLE
网易云已同步的歌单无法刷新歌曲变动，包括缺省就有的收藏

### ISSUE THREAD

**Issue by LiYefei** [mengkunsoft/MKOnlineMusicPlayer#58]
比如你先同步网易云，同步到了一批自己在网易云客户端建立好的歌单，以及默认就有的“收藏”歌单
之后你在网易云里修改歌单里的歌曲，比如删掉几首再加几首，然后重新点同步，会发现歌单并没有刷新
“收藏”歌单也是一样，新修改无法同步

**Comment by LiYefei** [comment]
基本确认是cache导致，应该可以在命名上增加trackupdatetime

**Comment by mengkunsoft** [comment]
这是程序主动添加的缓存。见 wiki https://github.com/mengkunsoft/MKOnlineMusicPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%92%AD%E6%94%BE%E5%99%A8%E7%BC%93%E5%AD%98%E9%97%AE%E9%A2%98
