### ISSUE TITLE
Thumbnails of some play lists don't show

### ISSUE THREAD

**Issue by mashirozx** [mengkunsoft/MKOnlineMusicPlayer#6]
musiclist.js like this:

![1](https://cloud.shino.cc/vfm-admin/thumbs/0a8d64d3047bf4332896529bf6044141-big.jpg)

But some pictures don't show like this:

![2](https://cloud.shino.cc/vfm-admin/thumbs/b006362bbe9f566f45fd847d28d7b042-big.jpg)

I've tried Chrome and MS Edge, none works.

But, I found the playlists imported by cloud music user ID show pictures normally.

![3](https://cloud.shino.cc/vfm-admin/thumbs/4733fefc45e1b245e97b70690d04d796-big.jpg)

I guess maybe the format of thumbnails different?

**Comment by mengkunsoft** [comment]
感谢反馈，这是一个已知的问题。已找到了问题原因，下一版本中进行修复！
（如不跳票的话，下一版本将在本周末发布）
