### ISSUE TITLE
疑似用于商业用途

### ISSUE THREAD

**Issue by Jsonkuln** [mengkunsoft/MKOnlineMusicPlayer#63]
http://www.gequdaquan.net/gqss/
![yzid n o 947o5pj7tc 7c](https://user-images.githubusercontent.com/34884230/51426659-ac824980-1c28-11e9-9b3a-26b81f6bff56.png)
![e6e1 b 2oft4yb mmi9 0 5](https://user-images.githubusercontent.com/34884230/51426666-c9b71800-1c28-11e9-81d7-4707e584fe43.png)

**Comment by zidanluo** [comment]
![image](https://user-images.githubusercontent.com/3350918/54073307-89872400-42c0-11e9-9ed8-e2de235fb76c.png)
这垃圾网站
