### ISSUE TITLE
给还在看这个项目的同学。

### ISSUE THREAD

**Issue by ScSofts** [mengkunsoft/MKOnlineMusicPlayer#72]
本人正在尝试使用React + (Node.JS || PHP || C++)重写。届时将支持多种后台api。界面是Material Design风格。

**Comment by Peter1303** [comment]
https://pdev.top/music/#neteaseList
我率先做好了 MD 风格

**Comment by ScSofts** [comment]
mdui这个库？功能少。。。而且一堆BUG

**Comment by Peter1303** [comment]
还可以啊，现在的功能ok的

**Comment by SunJiaJing90** [comment]
> 还可以啊，现在的功能ok的

老弟你这个风格做的不错，有没有提供下载歌曲功能呢？
