### ISSUE TITLE
[潜在的的问题]播放列表刷新时将自定义URL清空

### ISSUE THREAD

**Issue by Toxiad** [mengkunsoft/MKOnlineMusicPlayer#73]
由于平台音乐链接会失效,故播放器装载列表将会清空列表1或2（历史和正在播放）中的歌曲的url。通过这两个列表加载的所有音乐的url将会被刷掉。**如果在自定义列表填写了歌曲的url并从播放历史或正在播放列表播放的话也会被清空。**
改动较小的解决方法是直接修改`function.js`中的`loadList`。
判断列表并清空url的语句是`if (list == 1 || list == 2) tmpMusic.url = "";`，可以在前面加个判断来阻止
`if(tmpMusic.url_id != "toxiad") if (list == 1 || list == 2) tmpMusic.url = "";`
可以简单粗暴地搞定（

**Comment by Hu-Sea** [comment]
按照 Wiki 中的教程替换网易云的 Cookie ，列表还是只显示一首歌，可以播放网易云的歌曲，感觉不是 Cookie 的问题，还请有能力的大佬帮忙解决一下，另外我也看了一些其它人的 MKOnlineMusicPlayer ，发现从11月4号左右开始，都是列表只显示第一首歌。

**Comment by yl19850329** [comment]
2.3版本是正常的，现在从2.4降级到2.3

**Comment by yl19850329** [comment]
@Hu-Sea 留下QQ邮箱，给你发补丁。(2.4版可用.)

**Comment by Hu-Sea** [comment]
@yl19850329 yu_197@163.com 谢谢了

**Comment by Hu-Sea** [comment]
@yl19850329 26206086@qq.com
