### ISSUE TITLE
播放列表只显示一首歌，不知道该如何解决，替换Cookie后仍然无效

### ISSUE THREAD

**Issue by Hu-Sea** [mengkunsoft/MKOnlineMusicPlayer#75]

**Comment by Hu-Sea** [comment]
按照 Wiki 中的教程替换网易云的 Cookie ，列表还是只显示一首歌，可以播放网易云的歌曲，感觉不是 Cookie 的问题，还请有能力的大佬帮忙解决一下，另外我也看了一些其它人的 MKOnlineMusicPlayer ，发现从11月4号左右开始，都是列表只显示第一首歌。

**Comment by hucxsz** [comment]
同样的问题

**Comment by Hu-Sea** [comment]
11月8号  莫名其妙的自己又好了。。
