### ISSUE TITLE
挂进耻辱柱

### ISSUE THREAD

**Issue by annkoxx** [mengkunsoft/MKOnlineMusicPlayer#76]
http://www.gequdaquan.net/gqss/

疑似商业用途！
耻辱！
可耻！
开源作品添加登录注册！
曝光！
![QQ截图20201214115132](https://user-images.githubusercontent.com/50774548/102038662-cf144180-3e02-11eb-9cbf-de30be4e8561.png)
![QQ截图20201214115142](https://user-images.githubusercontent.com/50774548/102038664-d0456e80-3e02-11eb-8e3d-140c6a65dc84.png)
![QQ截图20201214115108](https://user-images.githubusercontent.com/50774548/102038666-d20f3200-3e02-11eb-8a1b-8f36288bb0d3.png)

**Comment by annkoxx** [comment]
音乐聚合官网可耻

**Comment by annkoxx** [comment]
此官网还有一个公众号！一样的作品盗用！！！！

**Comment by yl19850329** [comment]
@annkoxx 2.4不能使用了，麻烦更新一下呗。

**Comment by annkoxx** [comment]
> @annkoxx 2.4無法使用了，麻煩更新一下唄。

用2.3版本
