### ISSUE TITLE
bug: 列表播放死循环

### ISSUE THREAD

**Issue by GauharChan** [mengkunsoft/MKOnlineMusicPlayer#77]
歌曲没有资源播放不了的时候自动切换下一首，当整个列表都播放不了的时候，就会进入死循环🙁

**Comment by yl19850329** [comment]
留下QQ邮箱，给你发补丁。(2.4版可用.)

**Comment by maoxianshengdezaocha** [comment]
> 留下QQ邮箱，给你发补丁。（2.4版可用。）

1650356793@qq.com

**Comment by z131139** [comment]
> 留下QQ邮箱，给你发补丁。(2.4版可用.)

2644339467@qq.com

**Comment by F-fengzi** [comment]
> 留下QQ邮箱，给你发补丁。(2.4版可用.)

2772956447@qq.com

谢啦ヾ(≧▽≦*)o
我看代码是已经修了的，但是不管用

**Comment by F-fengzi** [comment]
找到问题了！
（前面留下qq邮箱会受到新的meting版本，https://github.com/metowolf/Meting，不过跟此问题无关）

2.4版本新增了连续失败10首，停止自动播放的功能
不过因为有BUG无法继续执行

BUG原因是在没声明数字的时候就使用了errCount++，我们需要在之前声明一下变量
**找到 js 目录下的 player.js，在30多行左右的 var rem = []; 下面，添加一句：**

**rem.errCount = 0;**

问题应该就修复了，如果有补充我会在下面说明
