### ISSUE TITLE
Api 调试模式已关闭

### ISSUE THREAD

**Issue by blogwy** [mengkunsoft/MKOnlineMusicPlayer#8]
我放到我服务器上，打开api接口页面显示 Api 调试模式已关闭 ，这个怎么弄？

**Comment by mengkunsoft** [comment]
Api 调试模式用于测试服务器环境，以便于定位程序运行故障原因。

正常使用情况下调试模式应该关闭。

如需开启调试模式，可以打开  api.php  ，将 `define('DEBUG', false);`  修改为 `define('DEBUG', true);`
